//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accurint_batch_setup
    {
        public string BATCH_ID { get; set; }
        public string BATCH_DESCR { get; set; }
        public string IMPORT_FILE_LAYOUT { get; set; }
        public Nullable<short> FTP_FROM_FILE_MANAGEMENT { get; set; }
        public byte[] FTP_FROM_RENAME_PATH { get; set; }
        public byte[] IMPORT_PATH { get; set; }
        public Nullable<short> IMPORT_FILE_MANAGEMENT { get; set; }
        public byte[] IMPORT_FILE_RENAME_PATH { get; set; }
        public Nullable<short> IMPORT_ACTION_TYPE { get; set; }
        public Nullable<short> IMPORT_ACTION_CODE { get; set; }
        public Nullable<short> IMPORT_STATUS_CODE { get; set; }
        public string IMPORT_WORKLIST_ID { get; set; }
        public Nullable<short> IMPORT_NEXT_CONTACT_ADV { get; set; }
        public string IMPORT_COMMENT { get; set; }
        public byte[] EXPORT_FIELDS { get; set; }
        public byte[] EXPORT_PATH { get; set; }
        public Nullable<short> EXPORT_FILE_MANAGEMENT { get; set; }
        public byte[] EXPORT_FILE_RENAME_PATH { get; set; }
        public Nullable<short> FTP_TO_FILE_MANAGEMENT { get; set; }
        public string EXPORT_COMMENT { get; set; }
        public byte[] EXPORT_CRITERIA { get; set; }
        public string FTP_USER_ID { get; set; }
        public string FTP_PASSWORD { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
