//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_sched
    {
        public string ACTION_ITEM_ID { get; set; }
        public string RUN_DATE { get; set; }
        public Nullable<int> ACTCODE_ID { get; set; }
        public string SCHEDULED { get; set; }
        public byte[] SCRIPT { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string TIME_STAMP { get; set; }
        public short TYPE { get; set; }
    }
}
