//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ardet
    {
        public int AR_ID { get; set; }
        public int ITEM_NO { get; set; }
        public string TRN_DATE { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> CHECK_NO { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public string CR_ID { get; set; }
        public string DB_ID { get; set; }
        public string TRUST_PERIOD { get; set; }
        public Nullable<short> TRUST_SUB_PERIOD { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
