//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assign
    {
        public int ITEM_NO { get; set; }
        public string WORKLIST_ID { get; set; }
        public string F_ALPHA { get; set; }
        public string T_ALPHA { get; set; }
        public Nullable<decimal> F_AMT { get; set; }
        public Nullable<decimal> T_AMT { get; set; }
        public Nullable<int> F_AGE { get; set; }
        public Nullable<int> T_AGE { get; set; }
        public string CLT_ID { get; set; }
        public string LANGUAGE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
