//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bureau_options
    {
        public string BUREAU_ID { get; set; }
        public string CTRL_NO { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string CREDIT_GRANTOR_CODE { get; set; }
        public string REPORTER_NAME { get; set; }
        public string REPORTER_FULL_ADDR { get; set; }
        public string REPORTER_PHONE { get; set; }
        public string ID_NO { get; set; }
    }
}
