//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart
    {
        public short CHART1 { get; set; }
        public string CASH { get; set; }
        public string RET_EARN { get; set; }
        public string PRINC_INCOME { get; set; }
        public string INT_INCOME { get; set; }
        public string FEE_INCOME { get; set; }
        public string CLT_DISB { get; set; }
        public string OVERPMT { get; set; }
        public string CLT_INCOME { get; set; }
        public string ACCT_PAY { get; set; }
        public string ACCT_REC { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
