//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clt
    {
        public string CLT_ID { get; set; }
        public string NAME { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string SALES_REP { get; set; }
        public string NEXT_CONTACT_DATE { get; set; }
        public string CLT_TYPE { get; set; }
        public string DEBT_TYPE { get; set; }
        public string BUREAU_PERMISSION { get; set; }
        public string BUREAU_REPORT { get; set; }
        public string COLLPLAN_ID { get; set; }
        public string FEEPLAN_ID { get; set; }
        public string CONTPLAN_ID { get; set; }
        public string TAX_ID { get; set; }
        public string TAX_EXEMPT { get; set; }
        public string REMIT_TYPE { get; set; }
        public string BALANCE_DEDUCT { get; set; }
        public string CREDIT_APPLY { get; set; }
        public string CREDIT_REFUND { get; set; }
        public string MASTER_ID { get; set; }
        public string STATUS_CODE { get; set; }
        public string FWD_AGENCY { get; set; }
        public Nullable<decimal> FWD_COLL_RATE { get; set; }
        public Nullable<short> PC_CONV_DELAY { get; set; }
        public string COMPANY_ID { get; set; }
        public Nullable<int> VER_LOCATION_CODE { get; set; }
        public Nullable<short> VER_STORE_GROUP { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string SCAN_STORE_NO { get; set; }
        public string SCAN_MERCHANT_ID { get; set; }
        public string NEXT_CONTACT_TIME { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string UDFPLAN_ID { get; set; }
        public string HIPAA_REG { get; set; }
        public string MATCH_TYPE { get; set; }
        public string EXTRA_STATEMENT_FIELD { get; set; }
        public string EXTRA_STATEMENT_LABEL { get; set; }
        public string TAXCODE_ID { get; set; }
        public string EMAIL { get; set; }
    }
}
