//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clt230_view
    {
        public int RECORD_ID { get; set; }
        public string COMPANY_ADDR1 { get; set; }
        public string COMPANY_CITY_ST_ZIP { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string COMPANY_FAX { get; set; }
        public string NAME { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CLT_ADDR1 { get; set; }
        public string CLT_CITY_ST_ZIP { get; set; }
        public string CLT_ID { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> LD_LIST_ACCTS { get; set; }
        public Nullable<decimal> LD_LIST_AMT { get; set; }
        public string AVG_MONTH_LIST { get; set; }
        public Nullable<int> LD_AVE_AGE { get; set; }
        public Nullable<decimal> LD_GROSS { get; set; }
        public Nullable<decimal> LD_RECOVER_PERCENT { get; set; }
        public Nullable<int> LD_RETURN_ACCTS { get; set; }
        public Nullable<decimal> LD_RETURN_AMT { get; set; }
        public Nullable<int> LD_ACTIVE_PAID_ACCTS { get; set; }
        public Nullable<decimal> LD_ACTIVE_PAID_AMT { get; set; }
        public string MASTER_ID { get; set; }
        public Nullable<decimal> RETURN_AMT { get; set; }
        public string ADDR1 { get; set; }
        public string STATUS_CODE { get; set; }
        public string CITY_ST_ZIP { get; set; }
        public Nullable<int> LD_AGE { get; set; }
    }
}
