//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clt_online
    {
        public int record_id { get; set; }
        public Nullable<int> clt_id { get; set; }
        public string name { get; set; }
        public Nullable<int> clt_enabled { get; set; }
        public Nullable<int> clt_type { get; set; }
        public string clt_user_id { get; set; }
        public string clt_user_pwd { get; set; }
        public Nullable<int> clt_user_enabled { get; set; }
        public Nullable<int> clt_user_type { get; set; }
    }
}
