//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cltrcvr
    {
        public string CLT_ID { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> LD_LIST_ACCTS { get; set; }
        public Nullable<int> LD_AGE { get; set; }
        public Nullable<decimal> LD_LIST_AMT { get; set; }
        public Nullable<int> LD_RETURN_ACCTS { get; set; }
        public Nullable<decimal> LD_RETURN_AMT { get; set; }
        public Nullable<decimal> LD_GROSS { get; set; }
        public Nullable<decimal> LD_NET { get; set; }
        public Nullable<int> RETURN_ACCTS { get; set; }
        public Nullable<decimal> RETURN_AMT { get; set; }
        public Nullable<decimal> GROSS { get; set; }
        public Nullable<decimal> NET { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<decimal> LD_CHARGEOFF_AMT { get; set; }
        public Nullable<decimal> LD_RETURN_PAID_AMT { get; set; }
        public Nullable<decimal> RETURN_PAID_AMT { get; set; }
    }
}
