//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collpdet
    {
        public string COLLPLAN_ID { get; set; }
        public int ITEM_NO { get; set; }
        public Nullable<double> COLL_RATE { get; set; }
        public Nullable<decimal> F_LIST_AMT { get; set; }
        public Nullable<decimal> T_LIST_AMT { get; set; }
        public Nullable<decimal> F_BALANCE { get; set; }
        public Nullable<decimal> T_BALANCE { get; set; }
        public Nullable<decimal> F_PMT_AMT { get; set; }
        public Nullable<decimal> T_PMT_AMT { get; set; }
        public Nullable<int> F_LIST_AGE { get; set; }
        public Nullable<int> T_LIST_AGE { get; set; }
        public Nullable<int> F_SERV_AGE { get; set; }
        public Nullable<int> T_SERV_AGE { get; set; }
        public string F_STATUS { get; set; }
        public string T_STATUS { get; set; }
        public Nullable<int> F_PLACE_AGE { get; set; }
        public Nullable<int> T_PLACE_AGE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
