//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class costs
    {
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public Nullable<decimal> CLERICAL_LABOR { get; set; }
        public Nullable<decimal> COLL_LABOR { get; set; }
        public Nullable<decimal> MGMT_LABOR { get; set; }
        public Nullable<decimal> OTHER_LABOR { get; set; }
        public Nullable<decimal> PRINTING { get; set; }
        public Nullable<decimal> MAILING { get; set; }
        public Nullable<decimal> LONG_DISTANCE { get; set; }
        public Nullable<decimal> SKIP_TRACING { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
