//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtrcbinq
    {
        public int DEBTOR_ID { get; set; }
        public int ITEM_NO { get; set; }
        public string USER_ID { get; set; }
        public string DEPARTMENT { get; set; }
        public string REQUESTED { get; set; }
        public string SUBMITTED { get; set; }
        public string RECEIVED { get; set; }
        public byte[] REQUEST_INFO { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
