//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtrrms
    {
        public int DEBTOR_ID { get; set; }
        public int ITEM_NO { get; set; }
        public string BANK_ID { get; set; }
        public Nullable<short> TYPE { get; set; }
        public string STATUS { get; set; }
        public string STATUS_DATE { get; set; }
        public Nullable<double> TRANS_AMOUNT { get; set; }
        public string OUT_RECORD { get; set; }
        public string PURGE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
