//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtrxdbt
    {
        public int DEBTOR_ID { get; set; }
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public Nullable<int> BUREAU_CODE { get; set; }
        public string BUREAU_DATE { get; set; }
        public Nullable<int> CHK_VER_CODE { get; set; }
        public string CHK_VER_TRANSIT_NO { get; set; }
        public string CHK_VER_ACCT_NO { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<int> SCAN_STATUS { get; set; }
    }
}
