//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtrltr
    {
        public int DEBTOR_ID { get; set; }
        public int ITEM_NO { get; set; }
        public Nullable<int> DEBT_ID { get; set; }
        public Nullable<short> DEBT_NO { get; set; }
        public string LETTER_TO_SEND { get; set; }
        public string DATE_TO_SEND { get; set; }
        public string LETTER_ADDR { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<short> TYPE { get; set; }
    }
}
