//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtr
    {
        public int DEBTOR_ID { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string SORT_NAME { get; set; }
        public string SSN1 { get; set; }
        public string SSN2 { get; set; }
        public string DOB1 { get; set; }
        public string DOB2 { get; set; }
        public string DL1 { get; set; }
        public string DL2 { get; set; }
        public string DL_STATE1 { get; set; }
        public string DL_STATE2 { get; set; }
        public string LANGUAGE { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_DATE { get; set; }
        public string DEBTOR_TYPE { get; set; }
        public string ASSIGN_ID { get; set; }
        public string NEXT_CONTACT_DATE { get; set; }
        public string NEXT_CONTACT_TIME { get; set; }
        public Nullable<int> AGCY_ATT_ID { get; set; }
        public string AGCY_ATT_DETAILS { get; set; }
        public Nullable<int> DBTR_ATT_ID { get; set; }
        public string DBTR_ATT_DETAILS { get; set; }
        public string PM_AUTH_REQ { get; set; }
        public string PM_AUTH_REC { get; set; }
        public Nullable<int> PROM_KEPT { get; set; }
        public Nullable<int> PROM_BROK { get; set; }
        public string REFERENCE_NO { get; set; }
        public string DIALER { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string RMS_ACCT_ID { get; set; }
        public Nullable<short> KENWOOD_CODE { get; set; }
        public string WARNING { get; set; }
    }
}
