//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtremp
    {
        public int DEBTOR_ID { get; set; }
        public int ITEM_NO { get; set; }
        public string NAME { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string DETAILS { get; set; }
        public string DUM_PHONE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<short> BUREAU_DBTRNAMEXEMP { get; set; }
    }
}
