//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class debttype
    {
        public string TYPE { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> STATUTE_YEARS { get; set; }
        public byte[] ICON { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string DBTRUDFPLAN_ID { get; set; }
        public string DEBTUDFPLAN_ID { get; set; }
    }
}
