//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class debtlgl
    {
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public string LEGAL_DATE { get; set; }
        public string LEGAL_COUNTY { get; set; }
        public string LEGAL_COURT_CODE { get; set; }
        public string LEGAL_CASE_NO { get; set; }
        public Nullable<decimal> LEGAL_INT { get; set; }
        public string FILING_DATE { get; set; }
        public string PROCESS_DATE { get; set; }
        public string PROCESS_SERVER { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
