//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class debt_bureau
    {
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public Nullable<short> BUREAU_PORTFOLIO_IND { get; set; }
        public string BUREAU_PORTFOLIO_NAME { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
