//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class debtfee
    {
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public int ITEM_NO { get; set; }
        public string FEE_CODE { get; set; }
        public Nullable<decimal> FEE_AMT { get; set; }
        public Nullable<decimal> FEE_PAID { get; set; }
        public Nullable<decimal> ADJUST_FEE { get; set; }
        public Nullable<decimal> THIS_REBATE_PAID { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
