//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class debtfwd
    {
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public string FWD_ID { get; set; }
        public Nullable<double> FWD_COLL_RATE { get; set; }
        public string FWD_DATE { get; set; }
        public byte[] FWD_TEXT { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
