//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dst
    {
        public int YEAR { get; set; }
        public string UTA_DST_ON { get; set; }
        public string EURO_DST_ON { get; set; }
        public string DST_OFF { get; set; }
    }
}
