//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eodlog
    {
        public string EOD_DATE { get; set; }
        public string NEXT_WORK_DAY { get; set; }
        public Nullable<short> STATION_SK { get; set; }
        public byte[] LOG { get; set; }
        public byte[] MODULES { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
