//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import
    {
        public string IMPORT_ID { get; set; }
        public string FILE { get; set; }
        public string DELIMITER { get; set; }
        public string END_OF_REC_MARK { get; set; }
        public Nullable<int> HEADER { get; set; }
        public Nullable<int> TRAILER { get; set; }
        public Nullable<int> IMPLIED_DECIMAL { get; set; }
        public string DATE_FORMAT { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<int> HEADER_LENGTH { get; set; }
    }
}
