//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indexing
    {
        public string TABLENAME { get; set; }
        public byte[] SEARCHFIELDS { get; set; }
        public byte[] DISPLAYSQL { get; set; }
        public byte[] CRITERIASQL { get; set; }
        public string IDFIELD { get; set; }
        public byte[] SORTSTRING { get; set; }
        public string XREFFILENAME { get; set; }
        public byte[] XREFFIELDS { get; set; }
        public byte[] MASTERFIELDNAMES { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
