//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        public string LETTER_ID { get; set; }
        public string DESCR { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public string DATA_SOURCE { get; set; }
        public string DATA_FILE { get; set; }
        public string FORM_TYPE { get; set; }
        public byte[] SELECTED_FIELDS { get; set; }
        public Nullable<int> OUTSOURCE_ID { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
