//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locktable
    {
        public string TABLENAME { get; set; }
        public string ID { get; set; }
        public string DB_ID { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<int> CONNECTION_NUMBER { get; set; }
        public Nullable<int> HNDL { get; set; }
    }
}
