//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchprm
    {
        public short ID { get; set; }
        public Nullable<int> NAME_SCORE { get; set; }
        public Nullable<int> SSN_SCORE { get; set; }
        public Nullable<int> DL_SCORE { get; set; }
        public Nullable<int> PHONE_SCORE { get; set; }
        public Nullable<int> ADDRESS_SCORE { get; set; }
        public Nullable<int> DOB_SCORE { get; set; }
        public Nullable<int> TOTAL_SCORE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
