//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class micrchk
    {
        public int MICRCHK_ID { get; set; }
        public string MICR { get; set; }
        public string TRANSIT_NO { get; set; }
        public string ABA_NO { get; set; }
        public string ACCT_NO { get; set; }
        public Nullable<int> CHECK_NO { get; set; }
        public string CHK_DATE { get; set; }
        public Nullable<decimal> CHK_AMT { get; set; }
        public string PAYER_NAME { get; set; }
        public string PAYER_ADDR1 { get; set; }
        public string PAYER_ADDR2 { get; set; }
        public string PAYER_CITY { get; set; }
        public string PAYER_ZIP { get; set; }
        public string PAYER_PHONE { get; set; }
        public string PAYEE_NAME { get; set; }
        public string PAYEE_ADDR1 { get; set; }
        public string PAYEE_ADDR2 { get; set; }
        public string PAYEE_CITY { get; set; }
        public string PAYEE_STATE { get; set; }
        public string PAYEE_ZIP { get; set; }
        public string PAYEE_PHONE { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ADDR1 { get; set; }
        public string BANK_ADDR2 { get; set; }
        public string BANK_CITY { get; set; }
        public string BANK_ZIP { get; set; }
        public string BANK_PHONE { get; set; }
        public string SIG_TEXT { get; set; }
        public string MEMO_TEXT { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
