//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmt
    {
        public int PMT_ID { get; set; }
        public Nullable<int> PMTB_ID { get; set; }
        public Nullable<int> DEBT_ID { get; set; }
        public Nullable<short> DEBT_NO { get; set; }
        public Nullable<int> DEBTOR_ID { get; set; }
        public string CLT_ID { get; set; }
        public string SALES_REP { get; set; }
        public string PMT_DATE { get; set; }
        public string PMT_CODE { get; set; }
        public string DIRECT { get; set; }
        public Nullable<int> CHECK_NO { get; set; }
        public string COLLPLAN_ID { get; set; }
        public string TRUST_POST_PERIOD { get; set; }
        public Nullable<decimal> OVERPMT { get; set; }
        public Nullable<decimal> OTHER_AGENCY_FEE { get; set; }
        public Nullable<decimal> PRINC_AMT { get; set; }
        public Nullable<decimal> CLT_PRINC_AMT { get; set; }
        public Nullable<decimal> INT_AMT { get; set; }
        public Nullable<decimal> SHOW_INT_AMT { get; set; }
        public Nullable<decimal> CLT_INT_AMT { get; set; }
        public Nullable<decimal> FEE_AMT { get; set; }
        public Nullable<decimal> SHOW_FEE_AMT { get; set; }
        public Nullable<decimal> CLT_FEE_AMT { get; set; }
        public Nullable<decimal> REBATE_AMT { get; set; }
        public Nullable<decimal> SALES_TAX_AMT { get; set; }
        public Nullable<int> BACKOUT_ID { get; set; }
        public Nullable<short> TRUST_POST_SUB_PERIOD { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<decimal> UNSHARED_INT_AMT { get; set; }
        public Nullable<decimal> UNSHARED_FEE_AMT { get; set; }
        public string POSTED_DATE { get; set; }
        public string WORKLIST_ID { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
    }
}
