//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmt_post_session
    {
        public int SESSION_ID { get; set; }
        public string SESSION_DATE_TIME { get; set; }
        public string POSTING_USER { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<int> SESSION_NUMBER { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
