//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmtbdebt
    {
        public int PMTB_ID { get; set; }
        public int DEBT_ID { get; set; }
        public short DEBT_NO { get; set; }
        public string PMT_DATE { get; set; }
        public Nullable<decimal> PRINC_AMT { get; set; }
        public Nullable<decimal> INT_AMT { get; set; }
        public Nullable<decimal> FEE_AMT { get; set; }
        public string NEW_STATUS { get; set; }
        public Nullable<int> BACKOUT_ID { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
