//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmtb
    {
        public int PMTB_ID { get; set; }
        public Nullable<int> CHECK_NO { get; set; }
        public string PMT_CODE { get; set; }
        public Nullable<decimal> PMT_AMT { get; set; }
        public Nullable<decimal> OTHER_AGENCY_FEE { get; set; }
        public Nullable<decimal> APPLIED_AMT { get; set; }
        public Nullable<int> DEBTOR_ID { get; set; }
        public string OTHER_AGENCY_ID { get; set; }
        public string PAYER_NAME { get; set; }
        public string PAYER_ADDR1 { get; set; }
        public string PAYER_ADDR2 { get; set; }
        public string PAYER_CITY { get; set; }
        public string PAYER_ZIP { get; set; }
        public string PAYER_DATE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string PMTB_USER { get; set; }
        public string MICR { get; set; }
    }
}
