//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmtfee
    {
        public int PMT_ID { get; set; }
        public int ITEM_NO { get; set; }
        public string FEE_CODE { get; set; }
        public Nullable<decimal> THIS_FEE_AMT { get; set; }
        public Nullable<decimal> THIS_SHOW_FEE_AMT { get; set; }
        public Nullable<decimal> THIS_CLT_FEE_AMT { get; set; }
        public Nullable<decimal> THIS_REBATE_AMT { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
