//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rmsbank
    {
        public string BANK_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string CLT_ID { get; set; }
        public Nullable<int> MAX_AGE { get; set; }
        public string CLOSING_STATUS { get; set; }
        public string INFO_REQUESTED_WORKLIST { get; set; }
        public string COLLPLAN_ID { get; set; }
        public string CONTPLAN_ID { get; set; }
        public string ORIG_CLT { get; set; }
        public string DEBT_TYPE { get; set; }
        public string FEEPLAN_ID { get; set; }
        public string STATUS_CODE { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
