//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stuser
    {
        public string USER_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string ST_PASSWORD { get; set; }
        public byte[] CLT_IDS { get; set; }
        public byte[] MENUGRANTS { get; set; }
        public byte[] WINDOWROGRANTS { get; set; }
        public byte[] WINDOWSETTINGS { get; set; }
        public byte[] COLLECTORDETWINS { get; set; }
        public string LABOR_TYPE { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public string THIN_CLT_LOCATION { get; set; }
        public string THIN_CLT_TIMEZONE { get; set; }
        public string THIN_CLT_DELTA { get; set; }
        public string TEMPLATE_ID { get; set; }
        public string TEAM { get; set; }
    }
}
