//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tzdet
    {
        public short ITEM_NO { get; set; }
        public short TZ_ID { get; set; }
        public short DST_TYPE { get; set; }
        public string ABBREV { get; set; }
        public string BEGIN_DT { get; set; }
        public string END_DT { get; set; }
        public Nullable<decimal> DST_DELTA { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
