//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userstat
    {
        public string USER_ID { get; set; }
        public string STAT_DATE { get; set; }
        public Nullable<int> WORKED { get; set; }
        public Nullable<double> TOTAL_TIME { get; set; }
        public Nullable<int> LETTERS { get; set; }
        public Nullable<int> PROMISES { get; set; }
        public Nullable<int> POST_DATES { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
