//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vend
    {
        public string VEND_ID { get; set; }
        public string COMPANY { get; set; }
        public string NAME { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public string COMMENTS { get; set; }
        public string TAX_ID { get; set; }
        public string ACCT_REF_NO { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
    }
}
