//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlaMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zip
    {
        public string ZIP1 { get; set; }
        public string CITY { get; set; }
        public string TIME_STAMP { get; set; }
        public string USER_ID_STAMP { get; set; }
        public Nullable<short> TIMEZONE { get; set; }
        public Nullable<short> DST_TYPE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string AREA_CODE { get; set; }
    }
}
